services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3001
      # if you want your backend to generate proper URLs for sharing:
      - API_BASE_URL=http://localhost:3001
      # AWS config (prod only)
      - AWS_REGION=us-west-2
      - DYNAMODB_TABLE=url-shortener
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      # Map container’s port 80 (nginx) to host 3000
      - "3000:80"
    depends_on:
      - backend
